### ISSUE TITLE
Add error handling

### ISSUE THREAD

**Issue by bhumijgupta** [socialbotspy/WhatsappPy#1]
Improve error handling, use try case block in case where error can occur

Example:
```python
def give_options():
    answer = int(...)
```
would throw error if the input cannot be converted to int

**Comment by ishandutta2007** [comment]
Thanks @bhumijgupta for sending https://github.com/socialbotspy/WhatsappPy/pull/2

Thought it shows the first commit as mine, but actually I am not the original author of the repo, so don't have much familiarity. In case you have spent some time in deep diving into the repo, would appreciate if you can spend some time to

1) enhance the documentations a bit. 
2) see if we can migrate from explicitly downloaded chromedriver to implicitly installable [`instapy-chromedriver`](https://pypi.org/project/instapy-chromedriver/) as requirements.

**Comment by bhumijgupta** [comment]
Sure, I'll look into it.
Currently this issue is resolved. I suggest we close this issue and open another issue for documentation and using installable chromedriver..

**Comment by bhumijgupta** [comment]
Closed by 5cd019c100adc9fa6960408515e9b40b245d345d

**Comment by ishandutta2007** [comment]
Sure go ahead and create one. For design, decorations, formating, styling, refactoring etc you are free to send a PR directly. but if you are building any core functionality you should create a issue and wait to get feedbacks.
